language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jurybulich22/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true jurybulich22/docker-react-sample npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-ap-south-1-847668753074"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
