language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jurybulich22/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true jurybulich22/docker-react-sample npm run test

